name: Testes Regressivos Cadastro e Login

on:
  pull_request:
    branches: [ main ]

jobs:
  RunTest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configurar Java 13
        uses: actions/setup-java@v3  # Atualizado para v3
        with:
          distribution: 'temurin'    # AdoptOpenJDK migrou para Eclipse Temurin
          java-version: '13'
          cache: 'maven'
          server-id: github           # Necessário para autenticação
          settings-path: ${{ github.workspace }}  # Caminho alternativo

      - name: Instalar Chrome
        run: |
          wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          rm google-chrome-stable_current_amd64.deb

      - uses: nanasess/setup-chromedriver@v1

      - name: Configurar display virtual
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &

      - name: Executar testes com Maven
        run: mvn -B test -Dtest=RunCucumber -Dbrowser=chrome-ci cluecumber-report:reporting